[package]
name = "arche-rs"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
bevy = "0.6"
rand = "0.8"
parry2d = "0.8"
nalgebra = { version = "0.30", features = ["convert-glam020"] }

[dev-dependencies]
approx = "0.5"